import React from 'react';
import { ShieldAlert, Gem, AlertTriangle, CheckCircle } from 'lucide-react';

export const DecoyMineralValidator: React.FC = () => {
  const amulets = [
    { name: 'Obsidian Eye', type: 'TRUE', mineral: 'Monte Arci Obsidian', verified: true, geology: 'Volcanic glass, Mount Arci.' },
    { name: 'Salt Basin Tear', type: 'FALSE_DECOY', mineral: 'Halite', verified: true, geology: 'Messinian salinity crisis deposits. Soluble. Corrupts other amulets.', threat: 'Dissolves upon activation, leaving user unprotected.' },
    { name: 'Nuraghic Bronze Core', type: 'TRUE', mineral: 'Arsenical Bronze', verified: true, geology: 'Ancient copper-arsenic alloy. Toxic if handled improperly.' },
  ];

  return (
    <div className="space-y-6">
      <div className="bg-stone-900 rounded-2xl border border-stone-800 p-6 shadow-xl">
        <h2 className="text-xl font-serif font-bold text-stone-100 flex items-center gap-2 mb-2">
          <Gem className="w-5 h-5 text-emerald-400" /> False Amulet & Mineral Geological Validator
        </h2>
        <p className="text-sm text-stone-400 mb-6">Cross-referencing Amulet properties with true Sardinian mineralogy. Identifying false artifacts generated by adversarial myths.</p>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-stone-800 text-xs font-mono uppercase tracking-wider text-stone-500">
                <th className="py-3 px-4">Artifact Name</th>
                <th className="py-3 px-4">Type</th>
                <th className="py-3 px-4">Mineral Requirement</th>
                <th className="py-3 px-4">Geological Accuracy</th>
                <th className="py-3 px-4">Risk Profile</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-800">
              {amulets.map((am, i) => (
                <tr key={i} className="hover:bg-stone-950/50 transition">
                  <td className="py-3 px-4 font-bold text-stone-200">{am.name}</td>
                  <td className="py-3 px-4">
                    <span className={`text-[10px] uppercase font-mono px-2 py-0.5 rounded border ${
                      am.type === 'TRUE' ? 'bg-emerald-950/30 text-emerald-400 border-emerald-900/50' : 'bg-rose-950/30 text-rose-400 border-rose-900/50'
                    }`}>
                      {am.type}
                    </span>
                  </td>
                  <td className="py-3 px-4 text-sm text-stone-300">{am.mineral}</td>
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-1.5 text-xs text-stone-400">
                      {am.verified ? <CheckCircle className="w-4 h-4 text-emerald-500" /> : <AlertTriangle className="w-4 h-4 text-amber-500" />}
                      <span className="truncate max-w-[200px]">{am.geology}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    {am.threat && (
                      <span className="flex items-center gap-1 text-xs text-rose-400 bg-rose-950/20 px-2 py-1 rounded border border-rose-900/50">
                        <AlertTriangle className="w-3 h-3" /> {am.threat}
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
